"""Idempotent seed script for FinPilot.

Seeds:
  - 13 merchants spanning apparel, electronics, books, grocery, home, beauty,
    sports, toys, pets, kitchenware, auto, fragrance, and fashion accessories
  - 10 products per merchant (130 total)
  - 1 agent_client per merchant, with a generated API key printed once to stdout
  - 14 demo users (1 buyer, 13 merchant admins), all with password Demo@1234

Safe to re-run: existing rows (matched by unique business key — merchant name,
product SKU, agent_client name, user email) are left untouched.

Run with:
    .venv\\Scripts\\python.exe -m app.seed.seed_data
"""

import secrets

from sqlalchemy.orm import Session

from app.core.security import hash_password, pwd_context
from app.models import Merchant, Product, AgentClient, User
from app.db.session import SessionLocal

DEMO_PASSWORD = "Demo@1234"

MERCHANTS = [
    {"key": "threadline", "name": "Threadline Apparel"},
    {"key": "circuithub", "name": "CircuitHub Electronics"},
    {"key": "pageturner", "name": "PageTurner Books"},
    {"key": "greenbasket", "name": "GreenBasket Grocery"},
    {"key": "homenest", "name": "HomeNest Furnishings"},
    {"key": "glowup", "name": "GlowUp Beauty"},
    {"key": "sprintzone", "name": "SprintZone Sports"},
    {"key": "tinytots", "name": "TinyTots Toys"},
    {"key": "pawpals", "name": "PawPals Pet Supplies"},
    {"key": "kitchencraft", "name": "KitchenCraft Essentials"},
    {"key": "autogear", "name": "AutoGear Motors"},
    {"key": "aromahome", "name": "AromaHome Fragrances"},
    {"key": "urbanstyle", "name": "UrbanStyle Accessories"},
]

PRODUCTS_BY_MERCHANT = {
    "threadline": [
        {
            "sku": "TL-SHOE-MEN-RUN-PRO",
            "name": "Men's Running Shoes Pro",
            "description": "Lightweight men's running shoe built for daily training miles.",
            "price_paise": 189900,
            "rating": 4.5,
            "category": "footwear",
            "attributes": {"color": "black", "size_range": "7-11", "gender": "men"},
        },
        {
            "sku": "TL-SHOE-WMN-RUN-AIR",
            "name": "Women's Running Shoes Air",
            "description": "Breathable women's running shoe with air cushioning.",
            "price_paise": 159900,
            "rating": 4.3,
            "category": "footwear",
            "attributes": {"color": "pink", "size_range": "5-9", "gender": "women"},
        },
        {
            "sku": "TL-SHOE-TRAIL-X",
            "name": "Trail Running Shoes X",
            "description": "Rugged trail runner with reinforced grip for off-road terrain.",
            "price_paise": 249900,
            "rating": 4.6,
            "category": "footwear",
            "attributes": {"color": "grey", "terrain": "trail"},
        },
        {
            "sku": "TL-TSHIRT-COTTON-CLASSIC",
            "name": "Classic Cotton T-Shirt",
            "description": "100% cotton crew-neck t-shirt, everyday essential.",
            "price_paise": 49900,
            "rating": 4.1,
            "category": "tops",
            "attributes": {"color": "white", "material": "cotton"},
        },
        {
            "sku": "TL-JEANS-SLIM-DENIM",
            "name": "Slim Fit Denim Jeans",
            "description": "Stretch denim jeans with a modern slim fit.",
            "price_paise": 129900,
            "rating": 4.2,
            "category": "bottoms",
            "attributes": {"color": "blue", "fit": "slim"},
        },
        {
            "sku": "TL-JACKET-WINDBREAKER",
            "name": "Windbreaker Jacket",
            "description": "Water-resistant windbreaker, packable for travel.",
            "price_paise": 179900,
            "rating": 4.4,
            "category": "outerwear",
            "attributes": {"color": "navy", "waterproof": True},
        },
        {
            "sku": "TL-SHIRT-FORMAL-COTTON",
            "name": "Formal Cotton Shirt",
            "description": "Wrinkle-resistant formal shirt for office wear.",
            "price_paise": 89900,
            "rating": 4.0,
            "category": "tops",
            "attributes": {"color": "light-blue", "fit": "regular"},
        },
        {
            "sku": "TL-PANTS-YOGA-TRACK",
            "name": "Yoga Track Pants",
            "description": "Four-way stretch track pants for yoga and lounging.",
            "price_paise": 79900,
            "rating": 4.3,
            "category": "bottoms",
            "attributes": {"color": "black", "material": "spandex-blend"},
        },
        {
            "sku": "TL-CAP-SPORTS",
            "name": "Sports Cap",
            "description": "Adjustable sports cap with moisture-wicking sweatband.",
            "price_paise": 34900,
            "rating": 3.9,
            "category": "accessories",
            "attributes": {"color": "red"},
        },
        {
            "sku": "TL-SNEAKERS-CANVAS",
            "name": "Canvas Sneakers",
            "description": "Casual canvas sneakers for everyday wear.",
            "price_paise": 109900,
            "rating": 4.0,
            "category": "footwear",
            "attributes": {"color": "white", "style": "casual"},
        },
    ],
    "circuithub": [
        {
            "sku": "CH-EARBUDS-BT-PRO",
            "name": "Wireless Bluetooth Earbuds Pro",
            "description": "True wireless earbuds with active noise cancellation.",
            "price_paise": 199900,
            "rating": 4.4,
            "category": "audio",
            "attributes": {"battery_hours": 24, "anc": True},
        },
        {
            "sku": "CH-HEADPHONES-X200",
            "name": "Over-Ear Headphones X200",
            "description": "Over-ear headphones with deep bass and long battery life.",
            "price_paise": 299900,
            "rating": 4.2,
            "category": "audio",
            "attributes": {"battery_hours": 30, "anc": False},
        },
        {
            "sku": "CH-SMARTWATCH-FIT3",
            "name": "Smartwatch Fit 3",
            "description": "Fitness smartwatch with GPS and 7-day battery.",
            "price_paise": 349900,
            "rating": 4.3,
            "category": "wearables",
            "attributes": {"battery_days": 7, "gps": True},
        },
        {
            "sku": "CH-POWERBANK-20K",
            "name": "Portable Power Bank 20000mAh",
            "description": "High-capacity power bank with fast charging support.",
            "price_paise": 149900,
            "rating": 4.5,
            "category": "accessories",
            "attributes": {"capacity_mah": 20000, "fast_charge": True},
        },
        {
            "sku": "CH-CHARGER-USBC-65W",
            "name": "USB-C Fast Charger 65W",
            "description": "Compact 65W USB-C GaN charger for laptops and phones.",
            "price_paise": 89900,
            "rating": 4.1,
            "category": "accessories",
            "attributes": {"wattage": 65},
        },
        {
            "sku": "CH-KEYBOARD-MECH-RGB",
            "name": "Mechanical Keyboard RGB",
            "description": "Hot-swappable mechanical keyboard with per-key RGB.",
            "price_paise": 279900,
            "rating": 4.6,
            "category": "computer-accessories",
            "attributes": {"switch_type": "blue", "backlight": "rgb"},
        },
        {
            "sku": "CH-MOUSE-WIRELESS-ERGO",
            "name": "Wireless Mouse Ergo",
            "description": "Ergonomic wireless mouse for all-day comfort.",
            "price_paise": 69900,
            "rating": 4.0,
            "category": "computer-accessories",
            "attributes": {"dpi": 1600, "wireless": True},
        },
        {
            "sku": "CH-SPEAKER-BOOM-MINI",
            "name": "Bluetooth Speaker Boom Mini",
            "description": "Compact waterproof Bluetooth speaker for outdoor use.",
            "price_paise": 129900,
            "rating": 4.2,
            "category": "audio",
            "attributes": {"waterproof": True, "battery_hours": 12},
        },
        {
            "sku": "CH-WEBCAM-1080P",
            "name": "1080p Webcam HD",
            "description": "Full HD webcam with autofocus for calls and streaming.",
            "price_paise": 159900,
            "rating": 3.9,
            "category": "computer-accessories",
            "attributes": {"resolution": "1080p", "fps": 30},
        },
        {
            "sku": "CH-STAND-LAPTOP-ALU",
            "name": "Laptop Stand Aluminum",
            "description": "Adjustable aluminum laptop stand for ergonomic setup.",
            "price_paise": 99900,
            "rating": 4.3,
            "category": "accessories",
            "attributes": {"material": "aluminum", "adjustable": True},
        },
    ],
    "pageturner": [
        {
            "sku": "PT-BOOK-ATOMIC-HABITS",
            "name": "Atomic Habits",
            "description": "A practical guide to building good habits and breaking bad ones.",
            "price_paise": 39900,
            "rating": 4.8,
            "category": "self-help",
            "attributes": {"author": "James Clear", "format": "paperback", "pages": 320},
        },
        {
            "sku": "PT-BOOK-DEEP-WORK",
            "name": "Deep Work",
            "description": "Rules for focused success in a distracted world.",
            "price_paise": 34900,
            "rating": 4.6,
            "category": "self-help",
            "attributes": {"author": "Cal Newport", "format": "paperback", "pages": 296},
        },
        {
            "sku": "PT-BOOK-SAPIENS",
            "name": "Sapiens: A Brief History of Humankind",
            "description": "A sweeping narrative of how Homo sapiens came to dominate the world.",
            "price_paise": 49900,
            "rating": 4.7,
            "category": "non-fiction",
            "attributes": {"author": "Yuval Noah Harari", "format": "paperback", "pages": 464},
        },
        {
            "sku": "PT-BOOK-PSYCH-MONEY",
            "name": "The Psychology of Money",
            "description": "Timeless lessons on wealth, greed, and happiness.",
            "price_paise": 32900,
            "rating": 4.7,
            "category": "finance",
            "attributes": {"author": "Morgan Housel", "format": "paperback", "pages": 256},
        },
        {
            "sku": "PT-BOOK-1984",
            "name": "1984",
            "description": "A dystopian classic about surveillance and totalitarian control.",
            "price_paise": 24900,
            "rating": 4.6,
            "category": "fiction",
            "attributes": {"author": "George Orwell", "format": "paperback", "pages": 328},
        },
        {
            "sku": "PT-BOOK-CLEAN-CODE",
            "name": "Clean Code",
            "description": "A handbook of agile software craftsmanship.",
            "price_paise": 59900,
            "rating": 4.4,
            "category": "technology",
            "attributes": {"author": "Robert C. Martin", "format": "paperback", "pages": 464},
        },
        {
            "sku": "PT-BOOK-ALCHEMIST",
            "name": "The Alchemist",
            "description": "A fable about following your dreams, told through a shepherd's journey.",
            "price_paise": 29900,
            "rating": 4.5,
            "category": "fiction",
            "attributes": {"author": "Paulo Coelho", "format": "paperback", "pages": 208},
        },
        {
            "sku": "PT-BOOK-THINKING-FAST-SLOW",
            "name": "Thinking, Fast and Slow",
            "description": "How two systems of thought shape our judgment and decisions.",
            "price_paise": 44900,
            "rating": 4.5,
            "category": "non-fiction",
            "attributes": {"author": "Daniel Kahneman", "format": "paperback", "pages": 499},
        },
        {
            "sku": "PT-BOOK-KIDS-STORYBOOK",
            "name": "The Golden Storybook Collection",
            "description": "An illustrated collection of bedtime stories for young readers.",
            "price_paise": 27900,
            "rating": 4.6,
            "category": "children",
            "attributes": {"format": "hardcover", "age_range": "4-8", "pages": 96},
        },
        {
            "sku": "PT-BOOK-NOTEBOOK-JOURNAL",
            "name": "Hardcover Ruled Journal",
            "description": "A premium ruled journal for notes, journaling, or planning.",
            "price_paise": 19900,
            "rating": 4.3,
            "category": "stationery",
            "attributes": {"pages": 192, "cover": "hardcover"},
        },
    ],
    "greenbasket": [
        {
            "sku": "GB-RICE-BASMATI-5KG",
            "name": "Premium Basmati Rice 5kg",
            "description": "Long-grain aged basmati rice, aromatic and fluffy when cooked.",
            "price_paise": 64900,
            "rating": 4.5,
            "category": "staples",
            "attributes": {"brand": "Golden Fields", "weight_kg": 5},
        },
        {
            "sku": "GB-OIL-SUNFLOWER-1L",
            "name": "Sunflower Cooking Oil 1L",
            "description": "Refined sunflower oil, light and suitable for everyday cooking.",
            "price_paise": 18900,
            "rating": 4.2,
            "category": "staples",
            "attributes": {"type": "sunflower", "volume_l": 1},
        },
        {
            "sku": "GB-DAL-TOOR-1KG",
            "name": "Toor Dal 1kg",
            "description": "Unpolished toor dal, rich in protein and fiber.",
            "price_paise": 15900,
            "rating": 4.4,
            "category": "staples",
            "attributes": {"type": "toor", "weight_kg": 1},
        },
        {
            "sku": "GB-TEA-MASALA-500G",
            "name": "Masala Tea 500g",
            "description": "Strong CTC tea blended with classic Indian spices.",
            "price_paise": 24900,
            "rating": 4.6,
            "category": "beverages",
            "attributes": {"type": "masala chai", "weight_g": 500},
        },
        {
            "sku": "GB-COFFEE-FILTER-200G",
            "name": "Filter Coffee Powder 200g",
            "description": "South Indian style filter coffee, coffee-chicory blend.",
            "price_paise": 29900,
            "rating": 4.5,
            "category": "beverages",
            "attributes": {"type": "filter coffee", "weight_g": 200},
        },
        {
            "sku": "GB-HONEY-ORGANIC-500G",
            "name": "Organic Honey 500g",
            "description": "Raw, unprocessed organic honey sourced from forest apiaries.",
            "price_paise": 39900,
            "rating": 4.7,
            "category": "condiments",
            "attributes": {"type": "organic", "weight_g": 500},
        },
        {
            "sku": "GB-SNACK-MIXTURE-400G",
            "name": "Spicy Namkeen Mixture 400g",
            "description": "A crunchy, spiced mix of lentils, nuts, and sev.",
            "price_paise": 12900,
            "rating": 4.1,
            "category": "snacks",
            "attributes": {"spice_level": "medium", "weight_g": 400},
        },
        {
            "sku": "GB-BISCUIT-DIGESTIVE-300G",
            "name": "Digestive Biscuits 300g",
            "description": "Wholewheat digestive biscuits, lightly sweetened.",
            "price_paise": 9900,
            "rating": 4.0,
            "category": "snacks",
            "attributes": {"weight_g": 300},
        },
        {
            "sku": "GB-ATTA-WHEAT-5KG",
            "name": "Whole Wheat Atta 5kg",
            "description": "Stone-ground whole wheat flour for soft rotis.",
            "price_paise": 27900,
            "rating": 4.3,
            "category": "staples",
            "attributes": {"weight_kg": 5},
        },
        {
            "sku": "GB-SPICE-GARAM-MASALA-100G",
            "name": "Garam Masala Powder 100g",
            "description": "A hand-blended mix of roasted whole spices.",
            "price_paise": 14900,
            "rating": 4.4,
            "category": "spices",
            "attributes": {"weight_g": 100},
        },
    ],
    "homenest": [
        {
            "sku": "HN-CUSHION-VELVET-SET2",
            "name": "Velvet Cushion Cover Set of 2",
            "description": "Plush velvet cushion covers that add a soft accent to any sofa.",
            "price_paise": 59900,
            "rating": 4.3,
            "category": "decor",
            "attributes": {"material": "velvet", "set_size": 2},
        },
        {
            "sku": "HN-LAMP-TABLE-LED",
            "name": "LED Table Lamp",
            "description": "Dimmable LED table lamp with a warm, ambient glow.",
            "price_paise": 89900,
            "rating": 4.4,
            "category": "lighting",
            "attributes": {"type": "LED", "dimmable": True},
        },
        {
            "sku": "HN-RUG-JUTE-5X7",
            "name": "Jute Area Rug 5x7 ft",
            "description": "Natural jute rug that brings warmth and texture to any room.",
            "price_paise": 249900,
            "rating": 4.5,
            "category": "flooring",
            "attributes": {"material": "jute", "size": "5x7 ft"},
        },
        {
            "sku": "HN-CURTAIN-BLACKOUT-SET2",
            "name": "Blackout Curtains Set of 2",
            "description": "Thermal-insulated blackout curtains that block light and noise.",
            "price_paise": 129900,
            "rating": 4.2,
            "category": "decor",
            "attributes": {"material": "polyester", "set_size": 2},
        },
        {
            "sku": "HN-WALLART-CANVAS-SET3",
            "name": "Abstract Canvas Wall Art Set of 3",
            "description": "A set of three framed abstract canvas prints.",
            "price_paise": 179900,
            "rating": 4.6,
            "category": "decor",
            "attributes": {"set_size": 3},
        },
        {
            "sku": "HN-CLOCK-WALL-WOODEN",
            "name": "Wooden Wall Clock",
            "description": "A minimalist wall clock with a solid wood frame.",
            "price_paise": 74900,
            "rating": 4.3,
            "category": "decor",
            "attributes": {"material": "wood"},
        },
        {
            "sku": "HN-STORAGE-BASKET-WICKER",
            "name": "Wicker Storage Basket",
            "description": "Handwoven wicker basket for stylish everyday storage.",
            "price_paise": 64900,
            "rating": 4.1,
            "category": "storage",
            "attributes": {"material": "wicker"},
        },
        {
            "sku": "HN-PLANTER-CERAMIC-SET3",
            "name": "Ceramic Planter Set of 3",
            "description": "Matte-finish ceramic planters in three sizes.",
            "price_paise": 89900,
            "rating": 4.5,
            "category": "decor",
            "attributes": {"material": "ceramic", "set_size": 3},
        },
        {
            "sku": "HN-MIRROR-WALL-ROUND",
            "name": "Round Wall Mirror",
            "description": "A slim-frame round mirror that opens up any space.",
            "price_paise": 119900,
            "rating": 4.4,
            "category": "decor",
            "attributes": {"shape": "round"},
        },
        {
            "sku": "HN-THROW-BLANKET-KNIT",
            "name": "Knitted Throw Blanket",
            "description": "A cozy cotton-knit throw for sofas and beds.",
            "price_paise": 99900,
            "rating": 4.2,
            "category": "textiles",
            "attributes": {"material": "cotton knit"},
        },
    ],
    "glowup": [
        {
            "sku": "GU-SERUM-VITC-30ML",
            "name": "Vitamin C Face Serum 30ml",
            "description": "Brightening serum with vitamin C to even out skin tone.",
            "price_paise": 59900,
            "rating": 4.5,
            "category": "skincare",
            "attributes": {"volume_ml": 30, "key_ingredient": "vitamin c"},
        },
        {
            "sku": "GU-MOISTURIZER-HYALURONIC-50ML",
            "name": "Hyaluronic Acid Moisturizer 50ml",
            "description": "Lightweight, deeply hydrating daily moisturizer.",
            "price_paise": 54900,
            "rating": 4.4,
            "category": "skincare",
            "attributes": {"volume_ml": 50},
        },
        {
            "sku": "GU-SUNSCREEN-SPF50-50ML",
            "name": "Sunscreen SPF 50 50ml",
            "description": "Broad-spectrum sunscreen with a non-greasy matte finish.",
            "price_paise": 44900,
            "rating": 4.6,
            "category": "skincare",
            "attributes": {"spf": 50, "volume_ml": 50},
        },
        {
            "sku": "GU-LIPSTICK-MATTE",
            "name": "Matte Liquid Lipstick",
            "description": "Long-wear matte liquid lipstick in a rich pigment.",
            "price_paise": 34900,
            "rating": 4.2,
            "category": "makeup",
            "attributes": {"finish": "matte"},
        },
        {
            "sku": "GU-FOUNDATION-LIQUID-30ML",
            "name": "Liquid Foundation 30ml",
            "description": "Buildable, medium-coverage liquid foundation.",
            "price_paise": 59900,
            "rating": 4.1,
            "category": "makeup",
            "attributes": {"volume_ml": 30},
        },
        {
            "sku": "GU-SHAMPOO-ARGAN-300ML",
            "name": "Argan Oil Shampoo 300ml",
            "description": "Sulfate-free shampoo enriched with argan oil.",
            "price_paise": 39900,
            "rating": 4.5,
            "category": "haircare",
            "attributes": {"volume_ml": 300},
        },
        {
            "sku": "GU-CONDITIONER-ARGAN-300ML",
            "name": "Argan Oil Conditioner 300ml",
            "description": "Deep-conditioning treatment for smooth, frizz-free hair.",
            "price_paise": 39900,
            "rating": 4.4,
            "category": "haircare",
            "attributes": {"volume_ml": 300},
        },
        {
            "sku": "GU-PERFUME-EDT-100ML",
            "name": "Eau de Toilette 100ml",
            "description": "A fresh floral-woody fragrance for everyday wear.",
            "price_paise": 129900,
            "rating": 4.6,
            "category": "fragrance",
            "attributes": {"volume_ml": 100},
        },
        {
            "sku": "GU-FACEMASK-SHEET-PACK10",
            "name": "Hydrating Sheet Mask Pack of 10",
            "description": "Aloe-infused sheet masks for an instant hydration boost.",
            "price_paise": 49900,
            "rating": 4.3,
            "category": "skincare",
            "attributes": {"pack_size": 10},
        },
        {
            "sku": "GU-NAILPOLISH-SET6",
            "name": "Nail Polish Set of 6",
            "description": "A curated set of six everyday nail polish shades.",
            "price_paise": 39900,
            "rating": 4.0,
            "category": "makeup",
            "attributes": {"set_size": 6},
        },
    ],
    "sprintzone": [
        {
            "sku": "SZ-YOGAMAT-6MM",
            "name": "Non-Slip Yoga Mat 6mm",
            "description": "Extra-thick, non-slip yoga mat with a carry strap.",
            "price_paise": 79900,
            "rating": 4.5,
            "category": "fitness",
            "attributes": {"thickness_mm": 6},
        },
        {
            "sku": "SZ-DUMBBELL-SET-10KG",
            "name": "Adjustable Dumbbell Set 10kg",
            "description": "Space-saving adjustable dumbbells for home workouts.",
            "price_paise": 199900,
            "rating": 4.4,
            "category": "fitness",
            "attributes": {"weight_kg": 10},
        },
        {
            "sku": "SZ-CRICKETBAT-KASHMIR",
            "name": "Kashmir Willow Cricket Bat",
            "description": "A balanced, full-size Kashmir willow cricket bat.",
            "price_paise": 149900,
            "rating": 4.3,
            "category": "cricket",
            "attributes": {"willow_type": "kashmir"},
        },
        {
            "sku": "SZ-FOOTBALL-SIZE5",
            "name": "Football Size 5",
            "description": "Match-quality size 5 football with a textured surface.",
            "price_paise": 69900,
            "rating": 4.4,
            "category": "football",
            "attributes": {"size": 5},
        },
        {
            "sku": "SZ-BADMINTON-RACKET-PRO",
            "name": "Badminton Racket Pro",
            "description": "Lightweight carbon-fiber racket for fast, controlled play.",
            "price_paise": 119900,
            "rating": 4.5,
            "category": "badminton",
            "attributes": {"material": "carbon fiber"},
        },
        {
            "sku": "SZ-SKIPPINGROPE-SPEED",
            "name": "Speed Skipping Rope",
            "description": "Ball-bearing speed rope for cardio and HIIT training.",
            "price_paise": 29900,
            "rating": 4.2,
            "category": "fitness",
            "attributes": {"type": "speed rope"},
        },
        {
            "sku": "SZ-RESISTANCEBAND-SET5",
            "name": "Resistance Band Set of 5",
            "description": "Five resistance levels for strength and mobility training.",
            "price_paise": 59900,
            "rating": 4.3,
            "category": "fitness",
            "attributes": {"set_size": 5},
        },
        {
            "sku": "SZ-CYCLINGHELMET",
            "name": "Cycling Helmet",
            "description": "Certified, well-ventilated helmet for road and city cycling.",
            "price_paise": 129900,
            "rating": 4.4,
            "category": "cycling",
            "attributes": {"certified": True},
        },
        {
            "sku": "SZ-GYMBAG-DUFFEL",
            "name": "Gym Duffel Bag",
            "description": "Spacious duffel bag with a separate shoe compartment.",
            "price_paise": 89900,
            "rating": 4.2,
            "category": "accessories",
            "attributes": {"capacity_l": 35},
        },
        {
            "sku": "SZ-WATERBOTTLE-1L",
            "name": "Sports Water Bottle 1L",
            "description": "Leak-proof, BPA-free water bottle with time markers.",
            "price_paise": 39900,
            "rating": 4.1,
            "category": "accessories",
            "attributes": {"volume_l": 1},
        },
    ],
    "tinytots": [
        {
            "sku": "TT-BLOCKS-BUILDING-100PC",
            "name": "Building Blocks Set 100pc",
            "description": "Colorful interlocking blocks that boost creativity.",
            "price_paise": 89900,
            "rating": 4.6,
            "category": "building-toys",
            "attributes": {"piece_count": 100},
        },
        {
            "sku": "TT-DOLL-FASHION",
            "name": "Fashion Doll with Accessories",
            "description": "A poseable fashion doll with a set of outfits.",
            "price_paise": 69900,
            "rating": 4.3,
            "category": "dolls",
            "attributes": {"age_range": "3-8"},
        },
        {
            "sku": "TT-PUZZLE-WOODEN-24PC",
            "name": "Wooden Jigsaw Puzzle 24pc",
            "description": "A chunky wooden puzzle for early learners.",
            "price_paise": 39900,
            "rating": 4.5,
            "category": "puzzles",
            "attributes": {"piece_count": 24},
        },
        {
            "sku": "TT-RCCAR-OFFROAD",
            "name": "Remote Control Off-Road Car",
            "description": "A rugged RC car built for rough terrain.",
            "price_paise": 149900,
            "rating": 4.4,
            "category": "remote-control",
            "attributes": {"battery_included": True},
        },
        {
            "sku": "TT-PLUSH-TEDDYBEAR-LARGE",
            "name": "Large Plush Teddy Bear",
            "description": "An extra-soft, huggable teddy bear.",
            "price_paise": 79900,
            "rating": 4.7,
            "category": "plush",
            "attributes": {"size": "large"},
        },
        {
            "sku": "TT-BOARDGAME-FAMILY",
            "name": "Family Board Game",
            "description": "A fast-paced board game for family game night.",
            "price_paise": 59900,
            "rating": 4.5,
            "category": "board-games",
            "attributes": {"players": "2-6"},
        },
        {
            "sku": "TT-KITCHENSET-PLAY",
            "name": "Play Kitchen Set",
            "description": "A pretend-play kitchen set with pots, pans, and food.",
            "price_paise": 129900,
            "rating": 4.4,
            "category": "pretend-play",
            "attributes": {"piece_count": 20},
        },
        {
            "sku": "TT-CRAYONS-SET24",
            "name": "Washable Crayons Set of 24",
            "description": "Vibrant, easy-wash crayons for young artists.",
            "price_paise": 19900,
            "rating": 4.2,
            "category": "art-supplies",
            "attributes": {"set_size": 24},
        },
        {
            "sku": "TT-BICYCLE-KIDS-16IN",
            "name": "Kids Bicycle 16 inch",
            "description": "A sturdy, training-wheel-ready bicycle for young riders.",
            "price_paise": 349900,
            "rating": 4.5,
            "category": "outdoor",
            "attributes": {"wheel_size_in": 16},
        },
        {
            "sku": "TT-SCOOTER-3WHEEL",
            "name": "3-Wheel Kick Scooter",
            "description": "A stable, easy-to-balance scooter for beginners.",
            "price_paise": 179900,
            "rating": 4.3,
            "category": "outdoor",
            "attributes": {"wheels": 3},
        },
    ],
    "pawpals": [
        {
            "sku": "PP-DOGFOOD-DRY-3KG",
            "name": "Dry Dog Food 3kg",
            "description": "Balanced nutrition kibble for adult dogs.",
            "price_paise": 89900,
            "rating": 4.5,
            "category": "dog-food",
            "attributes": {"weight_kg": 3},
        },
        {
            "sku": "PP-CATFOOD-DRY-2KG",
            "name": "Dry Cat Food 2kg",
            "description": "Complete dry food formulated for adult cats.",
            "price_paise": 69900,
            "rating": 4.4,
            "category": "cat-food",
            "attributes": {"weight_kg": 2},
        },
        {
            "sku": "PP-CATLITTER-CLUMPING-5KG",
            "name": "Clumping Cat Litter 5kg",
            "description": "Fast-clumping, odor-controlling cat litter.",
            "price_paise": 59900,
            "rating": 4.3,
            "category": "cat-supplies",
            "attributes": {"weight_kg": 5},
        },
        {
            "sku": "PP-DOGLEASH-NYLON",
            "name": "Nylon Dog Leash",
            "description": "A durable, comfortable-grip nylon leash.",
            "price_paise": 39900,
            "rating": 4.2,
            "category": "dog-accessories",
            "attributes": {"material": "nylon"},
        },
        {
            "sku": "PP-DOGBED-MEDIUM",
            "name": "Orthopedic Dog Bed Medium",
            "description": "Memory-foam dog bed for joint support and comfort.",
            "price_paise": 149900,
            "rating": 4.6,
            "category": "dog-accessories",
            "attributes": {"size": "medium"},
        },
        {
            "sku": "PP-CATTREE-SCRATCHER",
            "name": "Cat Tree Scratching Post",
            "description": "A multi-level cat tree with sisal scratching posts.",
            "price_paise": 199900,
            "rating": 4.5,
            "category": "cat-supplies",
            "attributes": {"height_ft": 4},
        },
        {
            "sku": "PP-PETSHAMPOO-OATMEAL",
            "name": "Oatmeal Pet Shampoo",
            "description": "Gentle, soothing shampoo for sensitive skin.",
            "price_paise": 34900,
            "rating": 4.4,
            "category": "grooming",
            "attributes": {"volume_ml": 250},
        },
        {
            "sku": "PP-CHEWTOY-DURABLE",
            "name": "Durable Chew Toy",
            "description": "A tough rubber chew toy for aggressive chewers.",
            "price_paise": 29900,
            "rating": 4.3,
            "category": "dog-toys",
            "attributes": {"material": "rubber"},
        },
        {
            "sku": "PP-BIRDCAGE-MEDIUM",
            "name": "Medium Bird Cage",
            "description": "A well-ventilated cage with multiple perches.",
            "price_paise": 179900,
            "rating": 4.2,
            "category": "bird-supplies",
            "attributes": {"size": "medium"},
        },
        {
            "sku": "PP-AQUARIUM-FILTER",
            "name": "Aquarium Filter Pump",
            "description": "A quiet, efficient filter for small to medium tanks.",
            "price_paise": 89900,
            "rating": 4.3,
            "category": "fish-supplies",
            "attributes": {"flow_rate_lph": 400},
        },
    ],
    "kitchencraft": [
        {
            "sku": "KC-COOKWARE-NONSTICK-SET5",
            "name": "Non-Stick Cookware Set of 5",
            "description": "A five-piece non-stick set for everyday cooking.",
            "price_paise": 249900,
            "rating": 4.5,
            "category": "cookware",
            "attributes": {"set_size": 5},
        },
        {
            "sku": "KC-KNIFE-CHEF-8IN",
            "name": "Chef's Knife 8 inch",
            "description": "A precision-forged stainless steel chef's knife.",
            "price_paise": 79900,
            "rating": 4.6,
            "category": "cutlery",
            "attributes": {"blade_length_in": 8},
        },
        {
            "sku": "KC-BLENDER-750W",
            "name": "Mixer Grinder Blender 750W",
            "description": "A powerful 750W blender with three jars.",
            "price_paise": 299900,
            "rating": 4.4,
            "category": "appliances",
            "attributes": {"wattage": 750},
        },
        {
            "sku": "KC-PRESSURECOOKER-5L",
            "name": "Pressure Cooker 5L",
            "description": "A reliable, energy-efficient 5-liter pressure cooker.",
            "price_paise": 189900,
            "rating": 4.5,
            "category": "cookware",
            "attributes": {"capacity_l": 5},
        },
        {
            "sku": "KC-DINNERSET-CERAMIC-16PC",
            "name": "Ceramic Dinner Set 16pc",
            "description": "A 16-piece ceramic dinnerware set for four.",
            "price_paise": 199900,
            "rating": 4.4,
            "category": "dinnerware",
            "attributes": {"piece_count": 16},
        },
        {
            "sku": "KC-STORAGE-AIRTIGHT-SET6",
            "name": "Airtight Storage Container Set of 6",
            "description": "Stackable, airtight containers for pantry staples.",
            "price_paise": 89900,
            "rating": 4.3,
            "category": "storage",
            "attributes": {"set_size": 6},
        },
        {
            "sku": "KC-TOASTER-2SLICE",
            "name": "2-Slice Pop-Up Toaster",
            "description": "A compact toaster with adjustable browning control.",
            "price_paise": 129900,
            "rating": 4.2,
            "category": "appliances",
            "attributes": {"slots": 2},
        },
        {
            "sku": "KC-CUTTINGBOARD-BAMBOO",
            "name": "Bamboo Cutting Board",
            "description": "A durable, knife-friendly bamboo cutting board.",
            "price_paise": 49900,
            "rating": 4.4,
            "category": "kitchen-tools",
            "attributes": {"material": "bamboo"},
        },
        {
            "sku": "KC-KETTLE-ELECTRIC-1.7L",
            "name": "Electric Kettle 1.7L",
            "description": "A fast-boiling kettle with auto shut-off.",
            "price_paise": 109900,
            "rating": 4.5,
            "category": "appliances",
            "attributes": {"capacity_l": 1.7},
        },
        {
            "sku": "KC-SPICERACK-ROTATING",
            "name": "Rotating Spice Rack",
            "description": "A 12-jar rotating rack that keeps spices within reach.",
            "price_paise": 64900,
            "rating": 4.1,
            "category": "storage",
            "attributes": {"jar_count": 12},
        },
    ],
    "autogear": [
        {
            "sku": "AG-SEATCOVER-CAR-SET",
            "name": "Car Seat Cover Set",
            "description": "A full set of tailored leatherette seat covers.",
            "price_paise": 249900,
            "rating": 4.3,
            "category": "car-accessories",
            "attributes": {"material": "leatherette"},
        },
        {
            "sku": "AG-HELMET-FULLFACE",
            "name": "Full Face Motorcycle Helmet",
            "description": "A certified full-face helmet with a scratch-resistant visor.",
            "price_paise": 299900,
            "rating": 4.6,
            "category": "safety",
            "attributes": {"certified": True},
        },
        {
            "sku": "AG-PHONEMOUNT-CAR",
            "name": "Car Phone Mount",
            "description": "A one-touch dashboard mount for hands-free navigation.",
            "price_paise": 39900,
            "rating": 4.2,
            "category": "car-accessories",
            "attributes": {"type": "dashboard mount"},
        },
        {
            "sku": "AG-DASHCAM-1080P",
            "name": "Dash Camera 1080p",
            "description": "A full-HD dash cam with loop recording and night vision.",
            "price_paise": 349900,
            "rating": 4.5,
            "category": "electronics",
            "attributes": {"resolution": "1080p"},
        },
        {
            "sku": "AG-CARVACUUM-PORTABLE",
            "name": "Portable Car Vacuum Cleaner",
            "description": "A compact, corded vacuum for quick interior clean-ups.",
            "price_paise": 149900,
            "rating": 4.4,
            "category": "car-care",
            "attributes": {"power_source": "12V DC"},
        },
        {
            "sku": "AG-TIREINFLATOR-ELECTRIC",
            "name": "Electric Tire Inflator",
            "description": "A digital tire inflator with a built-in pressure gauge.",
            "price_paise": 189900,
            "rating": 4.5,
            "category": "car-care",
            "attributes": {"max_psi": 150},
        },
        {
            "sku": "AG-BIKELOCK-DISC",
            "name": "Motorcycle Disc Lock",
            "description": "An alarmed disc lock that deters theft.",
            "price_paise": 79900,
            "rating": 4.3,
            "category": "safety",
            "attributes": {"alarm": True},
        },
        {
            "sku": "AG-CARPERFUME-GEL",
            "name": "Car Air Freshener Gel",
            "description": "A long-lasting gel air freshener for the car.",
            "price_paise": 19900,
            "rating": 4.0,
            "category": "car-accessories",
            "attributes": {"scent": "lavender"},
        },
        {
            "sku": "AG-GLOVES-RIDING",
            "name": "Motorcycle Riding Gloves",
            "description": "Knuckle-protected gloves for daily riding.",
            "price_paise": 89900,
            "rating": 4.4,
            "category": "safety",
            "attributes": {"material": "synthetic leather"},
        },
        {
            "sku": "AG-CARCHARGER-DUALUSB",
            "name": "Dual USB Car Charger",
            "description": "A fast-charging dual-port USB car charger.",
            "price_paise": 29900,
            "rating": 4.2,
            "category": "electronics",
            "attributes": {"ports": 2},
        },
    ],
    "aromahome": [
        {
            "sku": "AH-CANDLE-SOY-LAVENDER",
            "name": "Soy Wax Candle Lavender",
            "description": "A slow-burning soy candle with calming lavender.",
            "price_paise": 39900,
            "rating": 4.5,
            "category": "candles",
            "attributes": {"scent": "lavender", "wax_type": "soy"},
        },
        {
            "sku": "AH-CANDLE-SOY-SANDALWOOD",
            "name": "Soy Wax Candle Sandalwood",
            "description": "A warm, woody soy candle for cozy evenings.",
            "price_paise": 39900,
            "rating": 4.4,
            "category": "candles",
            "attributes": {"scent": "sandalwood", "wax_type": "soy"},
        },
        {
            "sku": "AH-DIFFUSER-REED-VANILLA",
            "name": "Reed Diffuser Vanilla",
            "description": "A long-lasting reed diffuser with a sweet vanilla scent.",
            "price_paise": 49900,
            "rating": 4.5,
            "category": "diffusers",
            "attributes": {"scent": "vanilla"},
        },
        {
            "sku": "AH-INCENSE-SANDALWOOD-PACK",
            "name": "Sandalwood Incense Sticks Pack",
            "description": "Hand-rolled incense sticks with a classic sandalwood note.",
            "price_paise": 14900,
            "rating": 4.3,
            "category": "incense",
            "attributes": {"stick_count": 20},
        },
        {
            "sku": "AH-ESSENTIALOIL-EUCALYPTUS",
            "name": "Eucalyptus Essential Oil 15ml",
            "description": "Pure eucalyptus oil for diffusers and aromatherapy.",
            "price_paise": 29900,
            "rating": 4.4,
            "category": "essential-oils",
            "attributes": {"volume_ml": 15},
        },
        {
            "sku": "AH-CANDLEHOLDER-BRASS",
            "name": "Brass Candle Holder",
            "description": "A handcrafted brass holder for pillar candles.",
            "price_paise": 59900,
            "rating": 4.2,
            "category": "accessories",
            "attributes": {"material": "brass"},
        },
        {
            "sku": "AH-ROOMSPRAY-JASMINE",
            "name": "Jasmine Room Spray",
            "description": "A fresh jasmine mist for instant room fragrance.",
            "price_paise": 34900,
            "rating": 4.3,
            "category": "sprays",
            "attributes": {"scent": "jasmine"},
        },
        {
            "sku": "AH-DIFFUSER-ELECTRIC-USB",
            "name": "Electric USB Aroma Diffuser",
            "description": "A quiet ultrasonic diffuser with color-changing light.",
            "price_paise": 89900,
            "rating": 4.5,
            "category": "diffusers",
            "attributes": {"power_source": "USB"},
        },
        {
            "sku": "AH-POTPOURRI-MIXED",
            "name": "Mixed Floral Potpourri",
            "description": "A fragrant bowl-ready mix of dried florals.",
            "price_paise": 24900,
            "rating": 4.1,
            "category": "decor",
            "attributes": {"weight_g": 150},
        },
        {
            "sku": "AH-GIFTSET-CANDLE-TRIO",
            "name": "Scented Candle Gift Set Trio",
            "description": "Three mini candles in a ready-to-gift box.",
            "price_paise": 99900,
            "rating": 4.6,
            "category": "gift-sets",
            "attributes": {"set_size": 3},
        },
    ],
    "urbanstyle": [
        {
            "sku": "US-WATCH-ANALOG-LEATHER",
            "name": "Analog Leather Strap Watch",
            "description": "A classic analog watch with a genuine leather strap.",
            "price_paise": 149900,
            "rating": 4.4,
            "category": "watches",
            "attributes": {"strap": "leather"},
        },
        {
            "sku": "US-SUNGLASSES-AVIATOR",
            "name": "Aviator Sunglasses",
            "description": "UV-protected aviator sunglasses with metal frames.",
            "price_paise": 89900,
            "rating": 4.3,
            "category": "eyewear",
            "attributes": {"uv_protection": True},
        },
        {
            "sku": "US-HANDBAG-TOTE",
            "name": "Canvas Tote Handbag",
            "description": "A roomy, durable canvas tote for everyday use.",
            "price_paise": 119900,
            "rating": 4.5,
            "category": "bags",
            "attributes": {"material": "canvas"},
        },
        {
            "sku": "US-WALLET-LEATHER-MEN",
            "name": "Men's Leather Wallet",
            "description": "A slim bifold wallet in genuine leather.",
            "price_paise": 69900,
            "rating": 4.4,
            "category": "wallets",
            "attributes": {"material": "leather"},
        },
        {
            "sku": "US-BACKPACK-LAPTOP",
            "name": "Laptop Backpack",
            "description": "A padded, water-resistant backpack for up to 15.6-inch laptops.",
            "price_paise": 159900,
            "rating": 4.5,
            "category": "bags",
            "attributes": {"laptop_size_in": 15.6},
        },
        {
            "sku": "US-BELT-LEATHER-FORMAL",
            "name": "Formal Leather Belt",
            "description": "A reversible leather belt for formal wear.",
            "price_paise": 49900,
            "rating": 4.2,
            "category": "belts",
            "attributes": {"material": "leather"},
        },
        {
            "sku": "US-JEWELRY-NECKLACE-SILVER",
            "name": "Silver Plated Necklace",
            "description": "A minimalist silver-plated pendant necklace.",
            "price_paise": 79900,
            "rating": 4.3,
            "category": "jewelry",
            "attributes": {"plating": "silver"},
        },
        {
            "sku": "US-EARRINGS-STUD-SET",
            "name": "Stud Earrings Set",
            "description": "A set of three everyday stud earring pairs.",
            "price_paise": 39900,
            "rating": 4.1,
            "category": "jewelry",
            "attributes": {"set_size": 3},
        },
        {
            "sku": "US-SCARF-SILK",
            "name": "Silk Scarf",
            "description": "A lightweight printed silk scarf.",
            "price_paise": 64900,
            "rating": 4.4,
            "category": "accessories",
            "attributes": {"material": "silk"},
        },
        {
            "sku": "US-CARDHOLDER-SLIM",
            "name": "Slim Card Holder Wallet",
            "description": "A pocket-friendly slim wallet with six card slots.",
            "price_paise": 39900,
            "rating": 4.2,
            "category": "wallets",
            "attributes": {"slots": 6},
        },
    ],
}

AGENT_CLIENTS = [
    {
        "merchant_key": "threadline",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 500000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "circuithub",
        "name": "Claude Desktop (test)",
        "max_order_amount_paise": 1000000,
        "max_orders_per_day": 5,
    },
    {
        "merchant_key": "pageturner",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 300000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "greenbasket",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 200000,
        "max_orders_per_day": 15,
    },
    {
        "merchant_key": "homenest",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 500000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "glowup",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 300000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "sprintzone",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 400000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "tinytots",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 400000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "pawpals",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 300000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "kitchencraft",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 500000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "autogear",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 500000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "aromahome",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 200000,
        "max_orders_per_day": 10,
    },
    {
        "merchant_key": "urbanstyle",
        "name": "Judge Demo Agent",
        "max_order_amount_paise": 300000,
        "max_orders_per_day": 10,
    },
]

USERS = [
    {"email": "admin.datainn@gmail.com", "role": "buyer", "merchant_key": None},
    {"email": "admin@threadline.demo", "role": "merchant_admin", "merchant_key": "threadline"},
    {"email": "admin@circuithub.demo", "role": "merchant_admin", "merchant_key": "circuithub"},
    {"email": "admin@pageturner.demo", "role": "merchant_admin", "merchant_key": "pageturner"},
    {"email": "admin@greenbasket.demo", "role": "merchant_admin", "merchant_key": "greenbasket"},
    {"email": "admin@homenest.demo", "role": "merchant_admin", "merchant_key": "homenest"},
    {"email": "admin@glowup.demo", "role": "merchant_admin", "merchant_key": "glowup"},
    {"email": "admin@sprintzone.demo", "role": "merchant_admin", "merchant_key": "sprintzone"},
    {"email": "admin@tinytots.demo", "role": "merchant_admin", "merchant_key": "tinytots"},
    {"email": "admin@pawpals.demo", "role": "merchant_admin", "merchant_key": "pawpals"},
    {"email": "admin@kitchencraft.demo", "role": "merchant_admin", "merchant_key": "kitchencraft"},
    {"email": "admin@autogear.demo", "role": "merchant_admin", "merchant_key": "autogear"},
    {"email": "admin@aromahome.demo", "role": "merchant_admin", "merchant_key": "aromahome"},
    {"email": "admin@urbanstyle.demo", "role": "merchant_admin", "merchant_key": "urbanstyle"},
]


def seed(db: Session) -> None:
    # --- Merchants ---
    merchants_by_key: dict[str, Merchant] = {}
    for m in MERCHANTS:
        existing = db.query(Merchant).filter(Merchant.name == m["name"]).one_or_none()
        if existing:
            merchants_by_key[m["key"]] = existing
            print(f"[skip] merchant already exists: {m['name']}")
        else:
            merchant = Merchant(name=m["name"])
            db.add(merchant)
            db.flush()
            merchants_by_key[m["key"]] = merchant
            print(f"[create] merchant: {m['name']}")

    # --- Products ---
    for merchant_key, products in PRODUCTS_BY_MERCHANT.items():
        merchant = merchants_by_key[merchant_key]
        for p in products:
            existing = db.query(Product).filter(Product.sku == p["sku"]).one_or_none()
            if existing:
                print(f"[skip] product already exists: {p['sku']}")
                continue
            product = Product(
                merchant_id=merchant.id,
                sku=p["sku"],
                name=p["name"],
                description=p["description"],
                price_paise=p["price_paise"],
                rating=p["rating"],
                category=p["category"],
                attributes=p["attributes"],
                is_active=True,
            )
            db.add(product)
            print(f"[create] product: {p['sku']} ({p['name']})")

    # --- Agent clients ---
    for ac in AGENT_CLIENTS:
        merchant = merchants_by_key[ac["merchant_key"]]
        existing = (
            db.query(AgentClient)
            .filter(AgentClient.name == ac["name"], AgentClient.merchant_id == merchant.id)
            .one_or_none()
        )
        if existing:
            print(f"[skip] agent_client already exists: {ac['name']}")
            continue
        plaintext_key = f"fp_live_{ac['merchant_key']}_{secrets.token_urlsafe(24)}"
        agent_client = AgentClient(
            merchant_id=merchant.id,
            name=ac["name"],
            api_key_hash=pwd_context.hash(plaintext_key),
            max_order_amount_paise=ac["max_order_amount_paise"],
            max_orders_per_day=ac["max_orders_per_day"],
            revoked=False,
        )
        db.add(agent_client)
        print(f"[create] agent_client: {ac['name']} (merchant={merchant.name})")
        print(f"         API KEY (save this now, shown only once): {plaintext_key}")

    # --- Users ---
    for u in USERS:
        existing = db.query(User).filter(User.email == u["email"]).one_or_none()
        if existing:
            print(f"[skip] user already exists: {u['email']}")
            continue
        merchant_id = merchants_by_key[u["merchant_key"]].id if u["merchant_key"] else None
        user = User(
            email=u["email"],
            password_hash=hash_password(DEMO_PASSWORD),
            role=u["role"],
            merchant_id=merchant_id,
        )
        db.add(user)
        print(f"[create] user: {u['email']} (role={u['role']}, password={DEMO_PASSWORD})")

    db.commit()


def main() -> None:
    db = SessionLocal()
    try:
        seed(db)
        print("\nSeed complete.")
    finally:
        db.close()


if __name__ == "__main__":
    main()
