"""add orders.payment_link column

Revision ID: 564ca48ee403
Revises: bb221903450f
Create Date: 2026-08-25 14:54:35.028699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '564ca48ee403'
down_revision: Union[str, None] = 'bb221903450f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('payment_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'payment_link')
    # ### end Alembic commands ###
