"""make conversations.merchant_id nullable for global chats

Revision ID: bb221903450f
Revises: 8bc38d4e3f28
Create Date: 2026-08-24 21:06:48.737002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb221903450f'
down_revision: Union[str, None] = '8bc38d4e3f28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'merchant_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'merchant_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
